In [ ]:
# Program 1: calculate total weekly energy from a list
daily_kwh=[400,800,400,390,500,600]
total_energy = sum(daily_kwh)
print("Total Energy Used:",total_energy,"kwh")

Total Energy Used: 3090 kwh

In [ ]:
# Program 2:Store building usage data
building_usage={
    "AIML":900,
    "Hostel":850
}
print("AIML used:",building_usage["AIML"], "kwh")

AIML used: 900 kwh

In [1]:
#calculate the bill
def calculate_bill(kwh,rate_per_unit):
  return kwh*rate_per_unit
todays_bill=calculate_bill(400,8)
print("today estimated bill is Rs:",todays_bill)

today estimated bill is Rs: 3200

In [20]:
#program 4
with open("campus_energy1.csv","r")as file:
  for line in file.readlines():
    print(line.strip())

﻿Date,Building,KWH_USE,PEAK_HOUR_USAGE
18-09-2026,CSE,400,510
19-09-2026,HOSTEL,900,680
20-09-2026,CSE,432,700
21-09-2026,CIVIL,600,800
22-09-2026,MECH,580,290
23-09-2026,ECE,400,800
24-09-2026,EEE,820,380
25-09-2026,HOSTEL,500,400
26-09-2026,CSE,650,790
27-09-2026,AIML,740,800
28-09-2026,AIDS,820,600
29-09-2026,CIVIL,500,850
30-09-2026,MECH,740,390
01-10-2026,CSE,470,680
02-10-2026,AIML,950,500
03-10-2026,AIDS,680,600
04-10-2026,EEE,840,570
05-10-2026,ECE,370,670
06-10-2026,CIVIL,760,680
,,,

In [40]:
#import the pandas libary
import pandas as pd
#load the dataset you created
df = pd.read_csv('campus_energy1.csv')
#Display the first few rows of the data
print("Here is the raw data:")
display(df.head())
#group the data to see total usage of the data
building_total = df.groupby('Building')['KWH_USE'].sum()
print("Total energy used by each building:")
print(building_total)
print("\nStatistical Summary:")
display(df.describe())

Here is the raw data:

         Date Building  KWH_USE  PEAK_HOUR_USAGE
0  18-09-2026      CSE    400.0            510.0
1  19-09-2026   HOSTEL    900.0            680.0
2  20-09-2026      CSE    432.0            700.0
3  21-09-2026    CIVIL    600.0            800.0
4  22-09-2026     MECH    580.0            290.0

Total energy used by each building:
Building
AIDS      1500.0
AIML      1690.0
CIVIL     1860.0
CSE       1952.0
ECE        770.0
EEE       1660.0
HOSTEL    1400.0
MECH      1320.0
Name: KWH_USE, dtype: float64

Statistical Summary:

          KWH_USE  PEAK_HOUR_USAGE
count   19.000000        19.000000
mean   639.578947       615.263158
std    183.977751       165.977523
min    370.000000       290.000000
25%    485.000000       505.000000
50%    650.000000       670.000000
75%    790.000000       745.000000
max    950.000000       850.000000

In [41]:
# Create the README.md file and write a message inside it
with open("README.md", "w") as file:
  file.write("# Smart Campus Energy Project\n")
  file.write("This repository contains my Week 1 hands-on Python and pandas assignments.\n")
  file.write("Created by: [ESWARI]")

print("README.md has been successfully created!")

README.md has been successfully created!